
export const list = [
  {
    id: 1,
    title: "Black pepper chicken and Rice",
    price: 35,
    img: "img/chinese 1.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 2,
    title: "Burger",
    price: 27,
    img: "img/american 1.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 3,
    title: "Jollof Rice and Fried Plantain",
    price: 50,
    img: "img/african 1.png",
    amount: 1,
    kind: "African",
  },
  {
    id: 4,
    title: "Noodle",
    price: 22,
    img: "img/chinese 2.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 5,
    title: "Hot dog",
    price: 10,
    img: "img/american 2.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 6,
    title: "White Rice and Vegetable Sauce with Plantain",
    price: 40,
    img: "img/african 2.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 7,
    title: "Fufu and Egusi Soup",
    price: 45,
    img: "img/african 3.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 8,
    title: "Hainanese chicken rice",
    price: 32,
    img: "img/chinese 3.jpg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 9,
    title: "Cobb salad",
    price: 25,
    img: "img/american 3.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 10,
    title: "Baked Apple Pie",
    price: 15,
    img: "img/american 4.jpg",
    amount: 1,
    kind: "American",
  },
  {
    id: 11,
    title: "Amala and Ewedu Soup",
    price: 28,
    img: "img/african 4.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 12,
    title: "Chinese Noodles",
    price: 30,
    img: "img/chinese 4.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 13,
    title: "Vetkoek (Fried Donuts Stuffed with Minced Meat)",
    price: 19,
    img: "img/african 5.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 14,
    title: "Seswaa",
    price: 25,
    img: "img/african 6.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 15,
    title: "Bacon, Eggs and Pancakes",
    price: 30,
    img: "img/american 5.jpg",
    amount: 1,
    kind: "American",
  },
  {
    id: 16,
    title: "Rice, Beans and Stew",
    price: 25,
    img: "img/african 7.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 17,
    title: "African Salad Abacha",
    price: 18,
    img: "img/african 8.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 18,
    title: "Kung Pao chicken",
    price: 21,
    img: "img/chinese 5.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 19,
    title: "Pancakes",
    price: 15,
    img: "img/american 6.jpeg",
    amount: 1,
    kind: "America",
  },
  {
    id: 20,
    title: "Gatsby Sandwich",
    price: 17,
    img: "img/african 10.jpg",
    amount: 1,
    kind: "African",
  },
];
