
export const list = [
  {
    id: 1,
    title: "Yellow 2-piece Joggers",
    price: 89,
    img: "img/chinese 1.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 2,
    title: "Burger",
    price: 143,
    img: "img/american 1.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 3,
    title: "Jollof Rice and Fried Plantain",
    price: 98,
    img: "img/african 1.png",
    amount: 1,
    kind: "African",
  },
  {
    id: 4,
    title: "Gray Jumpsuit",
    price: 57,
    img: "img/chinese 2.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 5,
    title: "Necklace, Earring and Ring Set",
    price: 49,
    img: "img/american 2.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 6,
    title: "White Rice and Vegetable Sauce with Plantain",
    price: 135,
    img: "img/african 2.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 7,
    title: "Fufu and Egusi Soup",
    price: 693,
    img: "img/african 3.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 8,
    title: "Peach Handbag",
    price: 289,
    img: "img/chinese 3.jpg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 9,
    title: "Earrings",
    price: 80,
    img: "img/american 3.jpeg",
    amount: 1,
    kind: "American",
  },
  {
    id: 10,
    title: "Black Boot Heel",
    price: 86,
    img: "img/american 4.jpg",
    amount: 1,
    kind: "American",
  },
  {
    id: 11,
    title: "Amala and Ewedu Soup",
    price: 120,
    img: "img/african 4.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 12,
    title: "Red-roped Heel",
    price: 157,
    img: "img/chinese 4.jpeg",
    amount: 1,
    kind: "Shoes",
  },
  {
    id: 13,
    title: "Red-roped Heel",
    price: 157,
    img: "img/african 5.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 14,
    title: "Red-roped Heel",
    price: 157,
    img: "img/african 6.jpg",
    amount: 1,
    kind: "African",
  },
  {
    id: 15,
    title: "Red-roped Heel",
    price: 157,
    img: "img/american 5.jpg",
    amount: 1,
    kind: "American",
  },
  {
    id: 16,
    title: "Rice, Beans and Stew",
    price: 157,
    img: "img/african 7.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 17,
    title: "Abacha",
    price: 157,
    img: "img/african 8.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 18,
    title: "Red-roped Heel",
    price: 157,
    img: "img/chinese 5.jpeg",
    amount: 1,
    kind: "Chinese",
  },
  {
    id: 19,
    title: "Pancakes",
    price: 157,
    img: "img/american 6.jpeg",
    amount: 1,
    kind: "America",
  },
  {
    id: 20,
    title: "Moi-Moi",
    price: 157,
    img: "img/african 9.jpeg",
    amount: 1,
    kind: "African",
  },
  {
    id: 21,
    title: "Shawarma",
    price: 157,
    img: "img/african 10.jpg",
    amount: 1,
    kind: "African",
  },
];
