const list = [
  {
    id: 1,
    title: "Yellow 2-piece Joggers",
    price: 89,
    img: "https://source.unsplash.com/nimElTcTNyY/600x300",
    amount: 1,
    kind: "Bags",
  },
  {
    id: 2,
    title: "Gold Earrings",
    price: 98,
    img: "https://source.unsplash.com/5ngCICAXiH0/600x300",
    amount: 1,
    kind: "Cloths",
  },
  {
    id: 3,
    title: "White Apple Watch",
    price: 143,
    img: "https://source.unsplash.com/2cFZ_FB08UM/600x300",
    amount: 1,
    kind: "Shoes-Jewelries",
  },
  {
    id: 4,
    title: "Gray Jumpsuit",
    price: 57,
    img: "https://source.unsplash.com/0UECcInuCR4/600x300",
    amount: 1,
    kind: "Bags",
  },
  {
    id: 5,
    title: "Necklace, Earring and Ring Set",
    price: 49,
    img: "https://source.unsplash.com/ZcLjr_Y2-z0/600x300",
    amount: 1,
    kind: "Shoes-Jewelries",
  },
  {
    id: 6,
    title: "Nike Sneakers",
    price: 135,
    img: "https://source.unsplash.com/jvoZ-Aux9aw/600x300",
    amount: 1,
    kind: "Cloths",
  },
  {
    id: 7,
    title: "SIlver and Pink Rhinestone Heel",
    price: 693,
    img: "https://source.unsplash.com/ndpX28miBtE/600x300",
    amount: 1,
    kind: "Shoes-Jewelries",
  },
  {
    id: 8,
    title: "Peach Handbag",
    price: 289,
    img: "https://source.unsplash.com/N8CwCRjp0LA/600x300",
    amount: 1,
    kind: "CLoths",
  },
  {
    id: 9,
    title: "Cloth",
    price: 80,
    img: "https://source.unsplash.com/sGX-7xDnuE0/600x300",
    amount: 1,
    kind: "Shoes-Jewelries",
  },
  {
    id: 10,
    title: "Black Boot Heel",
    price: 86,
    img: "https://source.unsplash.com/uianIkmhuvk/600x300",
    amount: 1,
    kind: "Bags",
  },
  {
    id: 11,
    title: "Black, Silver Prada Handbag",
    price: 120,
    img: "https://source.unsplash.com/jC2lLDk55CE/600x300",
    amount: 1,
    kind: "Shoes-Jewelries",
  },
  {
    id: 12,
    title: "Red-roped Heel",
    price: 157,
    img: "https://source.unsplash.com/be4eoee4who/600x300",
    amount: 1,
    kind: "Bags",
  },
];

export default list;